### ISSUE TITLE
Alexa support only brightness / on/off for SHCB-1 Shelly RGBW

### ISSUE THREAD

**Issue by IvoGruber** [Luligu/matterbridge-shelly#72]
Hello Luligu,

I am currently using version 1.0.4 of matterbridge-shelly with an SHCB-1 Shelly DUO RGBW within matterbridge  and connect this to Alexa. Alexa seems to support only changing brightness | and on|off but not colors or temperature this way. This problem existed even before version 0.9.5. I remember that with an older version it just supported color mode but I maybe mix this up with the [matterbridge-home-assistant-addon](https://github.com/t0bst4r/matterbridge-home-assistant-addon) plugin, that I tried out before.

Any chance to fix this or do I do something wrong?
If you need more information just give me a hint.

**Comment by tammeryousef1006** [comment]
hi @IvoGruber  , i got the same device and it shows colors correctly , follow these steps please and give feedback after : 
- unpair matterbridge from alexa 
- go to device page and set model to unknow as in the following screenshot 
![model](https://github.com/user-attachments/assets/90e7980c-41d9-45b2-99cd-1f1fce22c380)
- reset devices at matterbridge frontend to force new detection for the bulb
- pair to alexa again and check 

by the way are you using matterbridge at docker or you install it as standalone ?

**Comment by IvoGruber** [comment]
Hi @tammeryousef1006 ,

I followed these instructions. Device model was set to "9W E27" before in the shelly app, and is now set to "unknown". But the result is still the same after resettig devices in matterbridge and recommisioning. I get an Matterbridge aggregator in Alexa, a device in that aggregator for each shelly device including that and other bulbs of type "Sonstige" (other) and a light device connected to it of type "Lampe" (light) that allows to switch on/off and set brigthness. "Farbeinstellungen" (color preferences) is set to "Keine" (none).

I use matterbridge with docker.
Anything else I can try?

**Comment by tammeryousef1006** [comment]
Try deleting your Matterbridge docker and directories and create new one ,
this will force pulling the new settings of bulbs and other devices

**Comment by tammeryousef1006** [comment]
the main idea is to delete the json file of the bulb from /Matterbridge/matterbridge-shelly  , after that a reboot and new detection will fix all 

![json](https://github.com/user-attachments/assets/6d6624b4-433c-4705-ac17-52b55b4faac4)

if you cant do that then a fresh install will be better

**Comment by Luligu** [comment]
Hi,
are you sill using that the [matterbridge-home-assistant-addon](https://github.com/t0bst4r/matterbridge-home-assistant-addon) plugin?
Cause it doesn't work and never worked even before.

**Comment by Luligu** [comment]
> the main idea is to delete the json file of the bulb from /Matterbridge/matterbridge-shelly , after that a reboot and new detection will fix all
> 
> ![json](https://private-user-images.githubusercontent.com/62266828/378082226-6d6624b4-433c-4705-ac17-52b55b4faac4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzNTM1NjEsIm5iZiI6MTcyOTM1MzI2MSwicGF0aCI6Ii82MjI2NjgyOC8zNzgwODIyMjYtNmQ2NjI0YjQtNDMzYy00NzA1LWFjMTctNTJiNTViNGZhYWM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE5VDE1NTQyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlMzMzZWI4ZGUzMzU0YmM4NjZhMjM2MjcwNzNiYzk3MTU3ZWFiZGJkODY1NzQxZjAzZWFmNTY2NWVlNGZlNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EuWqNTmR6vFhw7eXuj4_o4GxOyj4DbWcgQwrtyfKmyc)
> 
> if you cant do that then a fresh install will be better

Or simply put the device id in the nocacheList.

**Comment by IvoGruber** [comment]
Hi,

also followed these instructions of @tammeryousef1006 and removed the docker folders. After reboot and new detection Alexa sees more devices now (I guess the blu stuff was disabled by config before, since I do not need it). But still no effect. The light still does support brightness setting only.

The json of the device looks like the attached file (just replaced the MAC and my ssid-name).
[shellycolorbulb-MAC.json](https://github.com/user-attachments/files/17446805/shellycolorbulb-MAC.json)

@Luligu I never used that addon, but a docker image, that was basically your matterbridge with the home-assistant plugin preinstalled. Yes, did not work as expected and removed it, even before t0bst4r announced a rewrite and not using matterbridge anymore.

**Comment by tammeryousef1006** [comment]
which version of matterbridge you see at frontend ?

**Comment by IvoGruber** [comment]
Version of matterbridge is 1.5.10 and version of the plugin is 1.0.4.
![Bildschirmfoto vom 2024-10-19 20-32-29](https://github.com/user-attachments/assets/5b7b9d5c-c865-4fbe-a92b-36ac6a7441e7)

**Comment by tammeryousef1006** [comment]
we will follow up about this issue , but one last try to put the device id in the nocacheList and restart as @Luligu suggest .
for me the two types of light already shows color once they set to known model , we will investigate this with rest of models

**Comment by IvoGruber** [comment]
Did even that, but unfortunately still no success.

**Comment by tammeryousef1006** [comment]
i already test both other models and reboot devices , at matterbridge I whitelist both and set them to nocachelist , after mb reboot and pair to alexa the devices shows colors correctly , are you on latest firmware 20230913-111548/v1.14.0-gcb84623 ? at devices page you Enable CoIoT and set CoIoT peer: mcast ?

**Comment by tammeryousef1006** [comment]
![shellybulb](https://github.com/user-attachments/assets/50b1de34-39d9-435b-b090-151431aa976c)

**Comment by tammeryousef1006** [comment]
![shellybulb](https://github.com/user-attachments/assets/7d9f7d00-384b-4e70-95dd-bb5845fd1b2d)
done enable Listen CoAp for color change commands

**Comment by IvoGruber** [comment]
@tammeryousef1006 it is all set like this. Yes I am using the newest version.

I tried to change the mode from "white" to "rgbw" in both locations of the json for the device in matterbridge and can now choose at least color after recommissioning but temperature is still not possible as in with the direct integration via shelly cloud in Alexa.

What is the value for "mode" in your json?

**Comment by tammeryousef1006** [comment]
ah i see , so now you can choose colors correctly but you cant choose colortemp if I understand you correctly , I don't have colortemp as well but just colors , will see in future if its possible to bring colortemp via matter to more controllers

**Comment by IvoGruber** [comment]
Yes, I still can not choose colortemp and it only works, because I adjust manually the json file. My feeling is, that this fix in [src/shellyDevice.ts](https://github.com/Luligu/matterbridge-shelly/commit/80a71f6c236bfd9e9a49987edaf1569d2612432e#diff-b7a72b34ff7139fa13524edc4cda99594a3bc64f5e19a0ff47ff10ab163ddebb) is not the doing its job?!

As far as I understand from older experiments with OpenHAB the device can change the mode from color to white or white to color (internally). In white mode you can set the color temperature and in color mode you can set the color. If you do not change the mode first you can not just change from warmwhite to red. OpenHAB seemed to struggel with that so i switched to Home Assistant which offered much better integrations anyway.

Changed mode in the json file now from "rgbw" to "color". Still can set the color now but no color temperature.

**Comment by IvoGruber** [comment]
So I played more with putting the device in the nocacheList, restarting matterbridge and recommisioning. It turns out that my assumtion seems to be true and if the bulb is in color mode at detection in matterbridge-shelly the device in Alexa allows to change colors. At least if I switch it to On/Red prio detection this happens. If have it off and in white mode the colors can't be changed later in Alexa.

**Comment by IvoGruber** [comment]
FYI: The device model option in the shelly app or config of the device it self is to tell the device which kind of socket it has. There are two devices out there. One with a socket E27 and one with GU10.  (I have both but only use the E27 type currently). Both also differ in there real life max and min color temperature. The GU10 model is also really bad with color picking via Alexa. It mostly does not fit. Asking for green gives a greenish yellow etc. I assume the devices are designed in a way that the firmware it self can not distinguish which type of the device it is, so Alterco Robotics later added this option?! But I have no idea if this has a real effect setting this option. At least this does not fix the color picking problem with GU10 version in Alexa.

**Comment by tammeryousef1006** [comment]
as i previously commented i did test also with choosing both models and the color was changing correctly , about colors not being very accurate its not matterbridge issue as you know , regarding colortemp and changing mode affection will take a look of that , I'm not expert with code but I know we have for example shelly 2.5 which can be working as roller cover or just two normal switches , so the code in general follow the device mode

**Comment by Luligu** [comment]
Hi,
sorry I was away.
What device do you have?
shellycolorbulb-XXXXXXXXX

**Comment by IvoGruber** [comment]
@tammeryousef1006, yes i also have a shelly 2.5 and several pm 2. first is used in switch mode, second with roller cover mode. For those its a fair assumtion that the user will not change the mode and you should present them as different matter devices. but for the bulbs its a killer feature to tell alexa (or what ever controller you use)  to switch from warm white to red to cold white. So its a bad idea to rely on the mode here at device detection and force the user to change the mode and than recommision the device.

As I understand now we actually have to issues. One is to implement the colortemp feature (its than more like a feature request than an issue) and the other on is to not rely on the mode for those bulb and always allow color setting in the matter device. Should we open new issues for those?!

**Comment by IvoGruber** [comment]
@Luligu I have shellycolorbulb-XXXXXXXXX (SHCB-1).

**Comment by Luligu** [comment]
Ok thanks.

That device has 2 running mode: color and white.

What mode are you using where you see problem?

You didn't answer to this:
are you sill using that the [matterbridge-home-assistant-addon](https://github.com/t0bst4r/matterbridge-home-assistant-addon) plugin?

**Comment by IvoGruber** [comment]
@Luligu as explained above: in white mode at detection time of the plugin I will not be able to change the color later in Alexa, just brightness. In color mode at detection time of the plugin I am able to change the color. Both modes do not allow to set the white color temperature later.

As I also said above I never used the addon since I have a container based setup of home assistant but I used a docker image with the home assistant plugin preinstalled provided by t0bst4r. I removed and skipped to the "original" docker image of matterbridge. It works anyway independent from the home assistant instance. I just embedded it there. So to keep it short: I do not use matterbridge-home-assistant-addon.

**Comment by Luligu** [comment]
Ok thanks.

In white mode with the current 1.0.4 is correct that you can only have brightness. Next release 1.0.5 will add support for a colorTemp ColorControl cluster.  Also used in shellybulbduo if you have them.

In color mode you should already have a regular RGB light (Hue and saturation in ColorControl cluster). In that mode there is no ColorTemp control so nothing to change there as you see in the device gui.
![image](https://github.com/user-attachments/assets/fd94b88b-f478-4114-a0df-fbddb1753e0c)

Release 1.0.5 should be tomorrow, just more time to test.
Unless you want to test the dev yourself. I would like it if you have time.

**Comment by IvoGruber** [comment]
@Luligu in general time is rare resource here and I won't make it to set up a dev environment tomorrow. So I guess for this change I will go the easy way and wait for the 1.0.5 release and check it than. But I guess it won't be the last issue I report since I have more shelly devices that I want to control via (alexa) voice commands without the need of the shelly cloud (and shelly skill). So if you drop me a hint on how to easily set up a dev environment for this plugin I will  try when ever free time pops up here.

**Comment by Luligu** [comment]
In my opinion, the easiest way is to use docker.

**Comment by Luligu** [comment]
## [1.0.5] - 2024-10-21

### Added

- [shelly]: Verified support for shellyhtg3 (Shelly H&T Gen 3) with new firmware 1.4.5-gbf870ca.
- [shelly]: Added event awake to save sleepy device cache file.
- [shelly]: Added scheduled_restart event from Sys to set the devices that will not be loaded from cache at restart.
- [shelly]: Added config_changed event from Sys to set the devices that will not be loaded from cache at restart.
- [shelly]: Added ota_begin, ota_progress and ota_success events from Sys to set the devices that will not be loaded from cache at restart.
- [shelly]: Added ColorTemp to Shelly Duo and Shelly Bulb in white mode.
- [cockpit]: Added cockpit dashboard 1.0


<a href="https://www.buymeacoffee.com/luligugithub">
  <img src="./yellow-button.png" alt="Buy me a coffee" width="120">
</a>

**Comment by IvoGruber** [comment]
@Luligu works for me as announced. Great job, thank you.
